import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ApolloProvider, ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client';
import LinkList from '../components/linkList';
import CreateLink from '../components/CreateLink';

const httpLink = createHttpLink({
  uri: 'http://graphql.kingnonso.com/',
});

const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache(),
});

export default function Home() {
  return (
    <div className={styles.container}>
      <ApolloProvider client={client}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <CreateLink />
      </ApolloProvider>

      <link rel='stylesheet' href='https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css' />
    </div>
  );
}
